const STORAGE_KEY='survey_studio_v2';
const app=document.getElementById('app');
const toastEl=document.getElementById('toast');
const TYPES={
  short:{label:'Short text',icon:'Aa'},long:{label:'Long text',icon:'¶'},single:{label:'Multiple choice',icon:'◉'},multi:{label:'Checkboxes',icon:'☑'},dropdown:{label:'Dropdown',icon:'⌄'},rating:{label:'Rating 1–5',icon:'★'},scale:{label:'Linear scale',icon:'↔'},yesno:{label:'Yes / No',icon:'✓'},email:{label:'Email',icon:'@'},number:{label:'Number',icon:'#'},date:{label:'Date',icon:'▣'}
};
const TEMPLATES={
  blank:{name:'Blank survey',description:'Start from scratch.',questions:[]},
  customer:{name:'Customer feedback',description:'Measure satisfaction and improvement areas.',questions:[['rating','Overall, how satisfied are you?',true],['single','How likely are you to use us again?',true,['Very likely','Likely','Not sure','Unlikely']],['long','What could we improve?',false]]},
  course:{name:'Course evaluation',description:'Collect structured student feedback.',questions:[['scale','How clearly was the course explained?',true],['scale','How useful were the learning activities?',true],['single','Was the workload reasonable?',true,['Yes','Mostly','No']],['long','What should be improved next time?',false]]},
  event:{name:'Event feedback',description:'Review an event while it is still fresh.',questions:[['rating','How would you rate the event overall?',true],['single','Did the event meet your expectations?',true,['Exceeded them','Met them','Partly','No']],['long','What was the most useful part?',false]]},
  pulse:{name:'Employee pulse',description:'A short team sentiment check.',questions:[['scale','How supported do you feel at work?',true],['scale','How manageable is your current workload?',true],['yesno','Would you recommend this workplace to others?',true],['long','What is one change that would help most?',false]]}
};
let db=null,auth=null,selectedQuestionId=null,saveTimer=null;
const state={cloud:false,user:null,surveys:[],responses:[],loading:true};

function uid(prefix='id'){return prefix+'_'+Math.random().toString(36).slice(2,10)+Date.now().toString(36).slice(-4)}
function esc(v=''){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function toast(msg){toastEl.textContent=msg;toastEl.classList.add('show');setTimeout(()=>toastEl.classList.remove('show'),2200)}
function fmtDate(v){try{return new Date(v).toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'})}catch{return '—'}}
function now(){return new Date().toISOString()}
function localLoad(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||{surveys:[],responses:[]}}catch{return {surveys:[],responses:[]}}}
function localSave(d){localStorage.setItem(STORAGE_KEY,JSON.stringify(d))}
function cloudConfigured(){const c=window.SURVEY_STUDIO_FIREBASE;return !!(c&&c.apiKey&&c.projectId&&window.firebase)}
function surveyById(id){return state.surveys.find(s=>s.id===id)}
function cloudBadge(){return state.cloud?'<span class="cloud-badge online">Cloud connected</span>':'<span class="cloud-badge demo">Demo storage</span>'}

async function init(){
  if(cloudConfigured()){
    try{
      if(!firebase.apps.length)firebase.initializeApp(window.SURVEY_STUDIO_FIREBASE);
      auth=firebase.auth();db=firebase.firestore();state.cloud=true;
      auth.onAuthStateChanged(async user=>{state.user=user||null;state.loading=false;if(user)await loadOwnedSurveys();else state.surveys=[];render()});
      return;
    }catch(e){console.error(e);toast('Cloud setup failed. Using demo storage.')}
  }
  const d=localLoad();state.surveys=d.surveys||[];state.responses=d.responses||[];state.loading=false;render();
}

async function loadOwnedSurveys(){
  if(!state.cloud||!state.user)return;
  const snap=await db.collection('surveys').where('ownerId','==',state.user.uid).get();
  state.surveys=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt)));
}
async function persistSurvey(s){
  if(state.cloud){await db.collection('surveys').doc(s.id).set(s,{merge:true})}
  else{const d=localLoad();const i=d.surveys.findIndex(x=>x.id===s.id);if(i>=0)d.surveys[i]=s;else d.surveys.unshift(s);localSave(d);state.surveys=d.surveys}
}
async function removeSurveyData(id){
  if(state.cloud){
    const rs=await db.collection('surveys').doc(id).collection('responses').get();
    const batch=db.batch();rs.docs.forEach(x=>batch.delete(x.ref));batch.delete(db.collection('surveys').doc(id));await batch.commit();await loadOwnedSurveys();
  }else{const d=localLoad();d.surveys=d.surveys.filter(s=>s.id!==id);d.responses=d.responses.filter(r=>r.surveyId!==id);localSave(d);state.surveys=d.surveys;state.responses=d.responses}
}
async function getPublicSurvey(id){
  if(state.cloud){const doc=await db.collection('surveys').doc(id).get();return doc.exists?{id:doc.id,...doc.data()}:null}
  return surveyById(id)||localLoad().surveys.find(s=>s.id===id)||null;
}
async function getResponses(id){
  if(state.cloud){const snap=await db.collection('surveys').doc(id).collection('responses').get();return snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>String(a.submittedAt).localeCompare(String(b.submittedAt)))}
  return localLoad().responses.filter(r=>r.surveyId===id);
}

function nav(){
  const user=state.user;const avatar=user?(user.displayName||user.email||'U').slice(0,2).toUpperCase():'MA';
  return `<header class="topbar"><a class="brand" href="#/"><span class="brand-mark">S</span><span>Survey Studio</span></a><div class="nav-actions">${cloudBadge()}<a class="btn btn-ghost hide-mobile" href="#/">My surveys</a>${(!state.cloud||user)?'<button class="btn btn-primary" onclick="openTemplatePicker()">+ New survey</button>':''}${state.cloud&&user?`<button class="avatar" title="${esc(user.email||'Account')}" onclick="signOutUser()">${esc(avatar)}</button>`:'<div class="avatar">MA</div>'}</div></header>`
}
function shell(content,includeNav=true){app.innerHTML=`<div class="app-shell">${includeNav?nav():''}${content}</div>`}
function loading(){shell('<main class="preview-wrap"><div class="card empty"><div class="spinner"></div><h3>Loading Survey Studio…</h3></div></main>',false)}

function authScreen(){
 shell(`<main class="auth-wrap"><section class="auth-intro"><div class="brand auth-brand"><span class="brand-mark">S</span><span>Survey Studio</span></div><h1>Create surveys people actually want to answer.</h1><p>Build, publish, collect responses, plus analyse results from one clean workspace.</p><div class="feature-points"><span>✓ Shared cloud responses</span><span>✓ Conditional question logic</span><span>✓ Templates and analytics</span></div></section><section class="card auth-card"><div class="auth-tabs"><button class="auth-tab active" onclick="setAuthMode('signin',this)">Sign in</button><button class="auth-tab" onclick="setAuthMode('signup',this)">Create account</button></div><h2 id="authTitle">Welcome back</h2><form onsubmit="emailAuth(event)"><input type="hidden" id="authMode" value="signin"><label>Email</label><input class="field" id="authEmail" type="email" required placeholder="you@example.com"><label>Password</label><input class="field" id="authPassword" type="password" minlength="6" required placeholder="At least 6 characters"><button class="btn btn-primary auth-submit" type="submit">Continue</button></form><div class="auth-divider"><span>or</span></div><button class="btn btn-secondary auth-submit" onclick="googleAuth()">Continue with Google</button><p class="tiny muted auth-note">Your surveys are private to your account. Published survey links are available to respondents.</p></section></main>`,false)
}
function setAuthMode(mode,el){document.getElementById('authMode').value=mode;document.getElementById('authTitle').textContent=mode==='signup'?'Create your account':'Welcome back';document.querySelectorAll('.auth-tab').forEach(x=>x.classList.remove('active'));el.classList.add('active')}
async function emailAuth(e){e.preventDefault();const email=document.getElementById('authEmail').value.trim(),password=document.getElementById('authPassword').value,mode=document.getElementById('authMode').value;try{if(mode==='signup')await auth.createUserWithEmailAndPassword(email,password);else await auth.signInWithEmailAndPassword(email,password)}catch(err){toast(err.message||'Could not sign in')}}
async function googleAuth(){try{await auth.signInWithPopup(new firebase.auth.GoogleAuthProvider())}catch(err){toast(err.message||'Google sign-in failed')}}
async function signOutUser(){if(auth)await auth.signOut()}

function templateToQuestions(key){return (TEMPLATES[key]?.questions||[]).map(spec=>{const [type,title,required,options]=spec;const q=defaultQuestion(type);q.title=title;q.required=!!required;if(options)q.options=options;return q})}
function openTemplatePicker(){
 const cards=Object.entries(TEMPLATES).map(([k,t])=>`<button class="template-card" onclick="createSurvey('${k}')"><span class="template-icon">${k==='blank'?'＋':k==='customer'?'★':k==='course'?'🎓':k==='event'?'◫':'♥'}</span><strong>${esc(t.name)}</strong><small>${esc(t.description)}</small></button>`).join('');
 document.body.insertAdjacentHTML('beforeend',`<div class="modal-backdrop" id="modal" onclick="if(event.target===this)this.remove()"><div class="modal template-modal"><h2>Start a new survey</h2><p>Choose a template or start with a blank page.</p><div class="template-grid">${cards}</div><div class="modal-actions"><button class="btn btn-secondary" onclick="document.getElementById('modal').remove()">Cancel</button></div></div></div>`)
}
async function createSurvey(template='blank'){
 if(state.cloud&&!state.user)return authScreen();
 const t=TEMPLATES[template]||TEMPLATES.blank;const id=uid('survey');const s={id,ownerId:state.user?.uid||'local',title:template==='blank'?'Untitled survey':t.name,description:t.description,questions:templateToQuestions(template),status:'draft',published:false,createdAt:now(),updatedAt:now(),theme:{brand:'#5b4ff6'}};
 state.surveys.unshift(s);await persistSurvey(s);document.getElementById('modal')?.remove();location.hash=`#/builder/${id}`
}
async function deleteSurvey(id){if(!confirm('Delete this survey and all its responses?'))return;await removeSurveyData(id);render();toast('Survey deleted')}
async function duplicateSurvey(id){const s=surveyById(id);if(!s)return;const copy=JSON.parse(JSON.stringify(s));copy.id=uid('survey');copy.title=s.title+' (copy)';copy.status='draft';copy.published=false;copy.createdAt=copy.updatedAt=now();copy.questions.forEach(q=>q.id=uid('q'));state.surveys.unshift(copy);await persistSurvey(copy);render();toast('Survey duplicated')}

async function dashboard(){
 if(state.cloud&&!state.user)return authScreen();
 if(state.cloud)await loadOwnedSurveys();const surveys=state.surveys;const live=surveys.filter(s=>s.published).length;
 const rows=surveys.map(s=>`<article class="card survey-row"><div><div class="survey-title">${esc(s.title)}</div><div class="survey-meta"><span class="status">${s.published?'Published':'Draft'}</span><span>${s.questions?.length||0} questions</span><span>Updated ${fmtDate(s.updatedAt)}</span></div></div><div class="row-actions"><a class="btn btn-secondary btn-sm" href="#/builder/${s.id}">Edit</a><a class="btn btn-secondary btn-sm" href="#/survey/${s.id}">Preview</a><a class="btn btn-secondary btn-sm" href="#/results/${s.id}">Results</a><button class="btn btn-ghost btn-sm" onclick="duplicateSurvey('${s.id}')">Duplicate</button><button class="btn btn-danger btn-sm" onclick="deleteSurvey('${s.id}')">Delete</button></div></article>`).join('');
 shell(`<main class="container"><section class="hero"><div><h1>Build better surveys.</h1><p>Choose a template, tailor the questions, publish, then watch responses come together.</p></div><button class="btn btn-primary" onclick="openTemplatePicker()">+ Create survey</button></section><section class="stats"><div class="stat"><div class="num">${surveys.length}</div><div class="label">Total surveys</div></div><div class="stat"><div class="num">${live}</div><div class="label">Published</div></div><div class="stat"><div class="num">${surveys.reduce((n,s)=>n+(s.questions?.length||0),0)}</div><div class="label">Questions created</div></div><div class="stat"><div class="num">${state.cloud?'Live':'Local'}</div><div class="label">Storage mode</div></div></section><div class="section-title"><div><h2>Your surveys</h2><p>Open a survey to edit, preview, share, or analyse it.</p></div></div>${rows?`<section class="survey-list">${rows}</section>`:`<section class="card empty"><div class="empty-icon">📝</div><h3>No surveys yet</h3><p>Start with a ready-made template or build your own.</p><button class="btn btn-primary" onclick="openTemplatePicker()">Create your first survey</button></section>`}</main>`)
}

function defaultQuestion(type){const q={id:uid('q'),type,title:TYPES[type].label,required:false,logic:null};if(['single','multi','dropdown'].includes(type))q.options=['Option 1','Option 2','Option 3'];if(type==='scale')q.scale={min:1,max:5,minLabel:'Low',maxLabel:'High'};return q}
async function mutateSurvey(sid,fn,rerender=true){const s=surveyById(sid);if(!s)return;fn(s);s.updatedAt=now();await persistSurvey(s);if(rerender)builder(sid)}
function addQuestion(sid,type){mutateSurvey(sid,s=>{const q=defaultQuestion(type);s.questions.push(q);selectedQuestionId=q.id},true)}
function updateSurvey(sid,patch){return mutateSurvey(sid,s=>Object.assign(s,patch),false)}
function updateQuestion(sid,qid,patch,rerender=false){return mutateSurvey(sid,s=>Object.assign(s.questions.find(q=>q.id===qid),patch),rerender)}
function changeType(sid,qid,type){const s=surveyById(sid),q=s?.questions.find(x=>x.id===qid);const patch={type};if(['single','multi','dropdown'].includes(type)&&!q.options)patch.options=['Option 1','Option 2','Option 3'];if(type==='scale'&&!q.scale)patch.scale={min:1,max:5,minLabel:'Low',maxLabel:'High'};updateQuestion(sid,qid,patch,true)}
function removeQuestion(sid,qid){mutateSurvey(sid,s=>{s.questions=s.questions.filter(q=>q.id!==qid);s.questions.forEach(q=>{if(q.logic?.sourceId===qid)q.logic=null});selectedQuestionId=null},true)}
function duplicateQuestion(sid,qid){mutateSurvey(sid,s=>{const i=s.questions.findIndex(q=>q.id===qid),q=JSON.parse(JSON.stringify(s.questions[i]));q.id=uid('q');q.logic=null;s.questions.splice(i+1,0,q);selectedQuestionId=q.id},true)}
function moveQuestion(sid,qid,dir){mutateSurvey(sid,s=>{const i=s.questions.findIndex(q=>q.id===qid),j=i+dir;if(j<0||j>=s.questions.length)return;[s.questions[i],s.questions[j]]=[s.questions[j],s.questions[i]]},true)}
function updateOption(sid,qid,index,value){const s=surveyById(sid),q=s.questions.find(x=>x.id===qid);q.options[index]=value;s.updatedAt=now();clearTimeout(saveTimer);saveTimer=setTimeout(()=>persistSurvey(s),300)}
function addOption(sid,qid){mutateSurvey(sid,s=>{const q=s.questions.find(x=>x.id===qid);q.options.push(`Option ${q.options.length+1}`)},true)}
function removeOption(sid,qid,index){const q=surveyById(sid)?.questions.find(x=>x.id===qid);if(q?.options?.length<=1)return toast('Keep at least one option');mutateSurvey(sid,s=>s.questions.find(x=>x.id===qid).options.splice(index,1),true)}
function setLogic(sid,qid,sourceId){const logic=sourceId?{sourceId,value:''}:null;updateQuestion(sid,qid,{logic},true)}
function setLogicValue(sid,qid,value){const q=surveyById(sid).questions.find(x=>x.id===qid);updateQuestion(sid,qid,{logic:{...(q.logic||{}),value}},false)}
function debounceSurvey(sid,patch){clearTimeout(saveTimer);saveTimer=setTimeout(()=>updateSurvey(sid,patch),300)}
async function publishSurvey(sid){const s=surveyById(sid);if(!s.questions.length)return toast('Add at least one question first');await mutateSurvey(sid,x=>{x.status='published';x.published=true},true);toast('Survey published')}
async function unpublishSurvey(sid){await mutateSurvey(sid,x=>{x.status='draft';x.published=false},true);toast('Survey moved to draft')}

function qEditor(sid,q,index,questions){
 const choice=['single','multi','dropdown'].includes(q.type)?`<div class="choice-list">${(q.options||[]).map((o,i)=>`<div class="choice-row"><span class="${q.type==='multi'?'box':'dot'}"></span><input class="field" value="${esc(o)}" oninput="updateOption('${sid}','${q.id}',${i},this.value)"><button class="icon-btn" onclick="removeOption('${sid}','${q.id}',${i})">✕</button></div>`).join('')}<button class="add-option" onclick="addOption('${sid}','${q.id}')">+ Add option</button></div>`:'';
 const placeholder=q.type==='long'?'<textarea class="field" rows="3" disabled placeholder="Long answer text"></textarea>':(['short','email','number','date'].includes(q.type)?`<input class="field" disabled placeholder="${TYPES[q.type].label} answer">`:q.type==='rating'?'<div class="muted">☆ ☆ ☆ ☆ ☆</div>':q.type==='scale'?'<div class="muted">1 &nbsp; 2 &nbsp; 3 &nbsp; 4 &nbsp; 5</div>':q.type==='yesno'?'<div class="muted">○ Yes &nbsp;&nbsp; ○ No</div>':'');
 const earlier=questions.slice(0,index);const logicOptions=earlier.map(x=>`<option value="${x.id}" ${q.logic?.sourceId===x.id?'selected':''}>${esc(x.title)}</option>`).join('');
 const logic=earlier.length?`<details class="logic-box" ${q.logic?'open':''}><summary>Branching / conditional logic</summary><div class="logic-grid"><label>Show this question only if<select class="select" onchange="setLogic('${sid}','${q.id}',this.value)"><option value="">Always show</option>${logicOptions}</select></label>${q.logic?`<label>Answer equals<input class="field" value="${esc(q.logic.value||'')}" oninput="setLogicValue('${sid}','${q.id}',this.value)" placeholder="Type the matching answer"></label>`:''}</div></details>`:'';
 return `<article id="q-${q.id}" class="card question-card ${selectedQuestionId===q.id?'active':''}" onclick="selectedQuestionId='${q.id}'"><div class="q-number">Question ${index+1}</div><div class="q-title"><input class="field" value="${esc(q.title)}" oninput="updateQuestion('${sid}','${q.id}',{title:this.value})"></div><select class="select" onchange="changeType('${sid}','${q.id}',this.value)">${Object.entries(TYPES).map(([k,t])=>`<option value="${k}" ${q.type===k?'selected':''}>${t.label}</option>`).join('')}</select>${choice||`<div style="margin-top:12px">${placeholder}</div>`}${logic}<div class="question-toolbar"><button class="btn btn-ghost btn-sm" onclick="event.stopPropagation();moveQuestion('${sid}','${q.id}',-1)" ${index===0?'disabled':''}>↑</button><button class="btn btn-ghost btn-sm" onclick="event.stopPropagation();moveQuestion('${sid}','${q.id}',1)" ${index===questions.length-1?'disabled':''}>↓</button><button class="btn btn-ghost btn-sm" onclick="event.stopPropagation();duplicateQuestion('${sid}','${q.id}')">Duplicate</button><label class="btn btn-ghost btn-sm"><input type="checkbox" ${q.required?'checked':''} onchange="updateQuestion('${sid}','${q.id}',{required:this.checked})"> Required</label><button class="btn btn-danger btn-sm" onclick="event.stopPropagation();removeQuestion('${sid}','${q.id}')">Delete</button></div></article>`
}
async function builder(sid){
 if(state.cloud&&!state.user)return authScreen();if(state.cloud&&!surveyById(sid))await loadOwnedSurveys();const s=surveyById(sid);if(!s)return location.hash='#/';
 const types=Object.entries(TYPES).map(([k,t])=>`<button class="question-type" onclick="addQuestion('${sid}','${k}')"><span class="qicon">${t.icon}</span>${t.label}</button>`).join('');
 const questions=(s.questions||[]).map((q,i)=>qEditor(sid,q,i,s.questions)).join('');const share=`${location.href.split('#')[0]}#/survey/${sid}`;
 shell(`<main class="container"><section class="hero"><div><div class="muted tiny">SURVEY BUILDER</div><h1 style="font-size:28px">${esc(s.title)}</h1></div><div class="row-actions"><a class="btn btn-secondary" href="#/survey/${sid}">Preview</a><a class="btn btn-secondary" href="#/results/${sid}">Results</a>${s.published?`<button class="btn btn-secondary" onclick="unpublishSurvey('${sid}')">Unpublish</button><button class="btn btn-primary" onclick="showShare('${sid}')">Share</button>`:`<button class="btn btn-primary" onclick="publishSurvey('${sid}')">Publish survey</button>`}</div></section><div class="builder-layout"><aside class="card panel sidebar"><h3>Add question</h3><div class="type-grid">${types}</div></aside><section class="canvas"><div class="card survey-head"><input class="title-input" value="${esc(s.title)}" oninput="debounceSurvey('${sid}',{title:this.value})"><textarea oninput="debounceSurvey('${sid}',{description:this.value})">${esc(s.description)}</textarea></div>${questions||`<div class="card empty"><div class="empty-icon">＋</div><h3>Add your first question</h3><p>Pick a question type from the panel.</p></div>`}</section><aside class="card panel inspector"><h3>Survey settings</h3><div class="setting-row"><div><strong>Status</strong><div class="tiny muted">Who can respond</div></div><span class="status">${s.published?'Published':'Draft'}</span></div><div class="setting-row"><div><strong>Questions</strong><div class="tiny muted">Total in survey</div></div><b>${s.questions.length}</b></div><div class="setting-row"><div><strong>Logic rules</strong><div class="tiny muted">Conditional questions</div></div><b>${s.questions.filter(q=>q.logic).length}</b></div>${s.published?`<div style="margin-top:14px"><div class="tiny muted" style="margin-bottom:7px">Public link</div><input class="field" value="${esc(share)}" readonly onclick="this.select()"><button class="btn btn-secondary" style="width:100%;margin-top:8px" onclick="copyText('${esc(share)}')">Copy link</button></div>`:''}${!state.cloud?'<div class="code-note" style="margin-top:14px">Demo mode uses this browser only. Add Firebase configuration to collect responses from other devices.</div>':''}</aside></div></main>`)
}
function showShare(sid){const url=`${location.href.split('#')[0]}#/survey/${sid}`;document.body.insertAdjacentHTML('beforeend',`<div class="modal-backdrop" id="modal" onclick="if(event.target===this)this.remove()"><div class="modal"><h2>Share your survey</h2><p>Anyone with this link can answer while the survey is published.</p><div class="share-box"><input class="field" id="shareLink" value="${esc(url)}" readonly><button class="btn btn-primary" onclick="copyText(document.getElementById('shareLink').value)">Copy</button></div>${!state.cloud?'<div class="code-note" style="margin-top:14px">Cloud storage is not configured yet. Responses from other devices will not reach this dashboard.</div>':''}<div class="modal-actions"><button class="btn btn-secondary" onclick="document.getElementById('modal').remove()">Close</button></div></div></div>`)}
async function copyText(t){try{await navigator.clipboard.writeText(t);toast('Link copied')}catch{toast('Copy the link manually')}}

function inputFor(q){const name=`q_${q.id}`,req=q.required?'required':'';if(q.type==='short')return `<input class="field" name="${name}" ${req} placeholder="Your answer">`;if(q.type==='long')return `<textarea class="field" rows="4" name="${name}" ${req} placeholder="Your answer"></textarea>`;if(q.type==='email')return `<input class="field" type="email" name="${name}" ${req} placeholder="name@example.com">`;if(q.type==='number')return `<input class="field" type="number" name="${name}" ${req}>`;if(q.type==='date')return `<input class="field" type="date" name="${name}" ${req}>`;if(q.type==='dropdown')return `<select class="select" name="${name}" ${req}><option value="">Choose an option</option>${(q.options||[]).map(o=>`<option value="${esc(o)}">${esc(o)}</option>`).join('')}</select>`;if(q.type==='single')return (q.options||[]).map(o=>`<label class="option"><input type="radio" name="${name}" value="${esc(o)}" ${req}> ${esc(o)}</label>`).join('');if(q.type==='multi')return (q.options||[]).map(o=>`<label class="option"><input type="checkbox" name="${name}" value="${esc(o)}"> ${esc(o)}</label>`).join('');if(q.type==='yesno')return `<label class="option"><input type="radio" name="${name}" value="Yes" ${req}> Yes</label><label class="option"><input type="radio" name="${name}" value="No" ${req}> No</label>`;if(q.type==='rating')return `<div class="scale">${[1,2,3,4,5].map(n=>`<label><input type="radio" name="${name}" value="${n}" ${req}>★ ${n}</label>`).join('')}</div>`;if(q.type==='scale')return `<div class="scale">${[1,2,3,4,5].map(n=>`<label><input type="radio" name="${name}" value="${n}" ${req}>${n}</label>`).join('')}</div><div class="scale-labels tiny muted"><span>${esc(q.scale?.minLabel||'Low')}</span><span>${esc(q.scale?.maxLabel||'High')}</span></div>`;return ''}
async function publicSurvey(sid){
 const s=await getPublicSurvey(sid);if(!s)return shell('<main class="preview-wrap"><div class="card empty"><h3>Survey not found</h3><p>This link may be incorrect or the survey was removed.</p></div></main>',false);
 const ownerPreview=state.user&&state.user.uid===s.ownerId;if(state.cloud&&!s.published&&!ownerPreview)return shell('<main class="preview-wrap"><div class="card empty"><h3>This survey is closed</h3><p>The owner is not accepting responses right now.</p></div></main>',false);
 const qs=(s.questions||[]).map((q,i)=>`<div class="public-q" data-qid="${q.id}" data-source="${q.logic?.sourceId||''}" data-value="${esc(q.logic?.value||'')}"><label class="title">${i+1}. ${esc(q.title)} ${q.required?'<span class="required">*</span>':''}</label>${inputFor(q)}</div>`).join('');
 shell(`<main class="preview-wrap"><form id="publicForm" class="card public-survey" onsubmit="submitResponse(event,'${sid}')" oninput="applyLogic()" onchange="applyLogic()"><div class="cover" style="background:${esc(s.theme?.brand||'#5b4ff6')}"></div><div class="public-head"><div class="tiny muted" style="margin-bottom:7px">SURVEY</div><h1>${esc(s.title)}</h1><p>${esc(s.description)}</p>${ownerPreview?'<div class="preview-badge">Owner preview</div>':''}</div><div class="public-body">${qs||'<div class="empty"><p>This survey has no questions yet.</p></div>'}${qs?`<button class="btn btn-primary" type="submit" style="margin-top:22px" ${ownerPreview?'disabled title="Publish the survey to collect responses"':''}>Submit response</button>`:''}</div></form><div class="tiny muted powered">Powered by Survey Studio</div></main>`,false);applyLogic()
}
function answerFromForm(form,qid){const els=[...form.elements].filter(x=>x.name===`q_${qid}`);if(!els.length)return '';if(els[0].type==='checkbox')return els.filter(x=>x.checked).map(x=>x.value);if(['radio'].includes(els[0].type))return els.find(x=>x.checked)?.value||'';return els[0].value||''}
function applyLogic(){const form=document.getElementById('publicForm');if(!form)return;document.querySelectorAll('.public-q').forEach(section=>{const source=section.dataset.source;if(!source){section.hidden=false;section.querySelectorAll('input,textarea,select').forEach(x=>x.disabled=false);return}const actual=answerFromForm(form,source),expected=section.dataset.value;const visible=Array.isArray(actual)?actual.includes(expected):String(actual)===String(expected);section.hidden=!visible;section.querySelectorAll('input,textarea,select').forEach(x=>x.disabled=!visible)})}
async function submitResponse(e,sid){
 e.preventDefault();const s=await getPublicSurvey(sid);if(!s)return;applyLogic();const fd=new FormData(e.target),answers={};
 for(const q of s.questions){const section=e.target.querySelector(`[data-qid="${q.id}"]`);if(section?.hidden)continue;const name=`q_${q.id}`;answers[q.id]=q.type==='multi'?fd.getAll(name):(fd.get(name)||'');if(q.required&&(q.type==='multi'?!answers[q.id].length:!answers[q.id]))return toast(`Please answer: ${q.title}`)}
 const response={surveyId:sid,answers,submittedAt:now(),userAgent:navigator.userAgent.slice(0,180)};
 try{if(state.cloud)await db.collection('surveys').doc(sid).collection('responses').add(response);else{const d=localLoad();response.id=uid('response');d.responses.push(response);localSave(d);state.responses=d.responses}e.target.outerHTML=`<div class="card success-box"><div class="success-check">✓</div><h2>Response submitted</h2><p>Thank you. Your feedback has been recorded.</p></div>`;window.scrollTo({top:0,behavior:'smooth'})}catch(err){console.error(err);toast('Could not submit this response')}
}

function resultBlock(q,responses){
 const vals=responses.map(r=>r.answers?.[q.id]).filter(v=>Array.isArray(v)?v.length:v!==''&&v!=null);if(['single','dropdown','yesno','rating','scale','multi'].includes(q.type)){let labels=[];if(['single','dropdown','multi'].includes(q.type))labels=q.options||[];else if(q.type==='yesno')labels=['Yes','No'];else labels=['1','2','3','4','5'];const counts=Object.fromEntries(labels.map(l=>[String(l),0]));vals.forEach(v=>Array.isArray(v)?v.forEach(x=>counts[x]=(counts[x]||0)+1):counts[String(v)]=(counts[String(v)]||0)+1);const total=Math.max(1,vals.length);const avg=['rating','scale'].includes(q.type)&&vals.length?(vals.reduce((n,v)=>n+Number(v),0)/vals.length).toFixed(2):null;return `<div class="result-card card"><div class="result-heading"><h3>${esc(q.title)}</h3>${avg?`<span class="avg-pill">Average ${avg}/5</span>`:''}</div>${Object.entries(counts).map(([k,n])=>`<div class="bar-row"><span class="tiny">${esc(k)}</span><div class="bar-track"><div class="bar-fill" style="width:${(n/Math.max(1,...Object.values(counts)))*100}%"></div></div><span class="tiny">${n} · ${Math.round(n/total*100)}%</span></div>`).join('')}<div class="tiny muted result-foot">${vals.length} answered</div></div>`}return `<div class="result-card card"><h3>${esc(q.title)}</h3>${vals.length?vals.slice().reverse().slice(0,20).map(v=>`<span class="answer-chip">${esc(Array.isArray(v)?v.join(', '):v)}</span>`).join(''):'<div class="muted tiny">No answers yet.</div>'}<div class="tiny muted result-foot">${vals.length} answered</div></div>`
}
function calcCompletion(s,rs){if(!rs.length||!s.questions.length)return 0;const total=rs.reduce((sum,r)=>sum+s.questions.filter(q=>{const v=r.answers?.[q.id];return Array.isArray(v)?v.length:v!==''&&v!=null}).length,0);return Math.round(total/(rs.length*s.questions.length)*100)}
function exportCSV(sid,rs){const s=surveyById(sid);const header=['Submitted at',...s.questions.map(q=>q.title)];const rows=rs.map(r=>[r.submittedAt,...s.questions.map(q=>Array.isArray(r.answers?.[q.id])?r.answers[q.id].join(' | '):r.answers?.[q.id]||'')]);const csv=[header,...rows].map(row=>row.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(s.title||'survey').replace(/[^a-z0-9]+/gi,'_')+'_responses.csv';a.click();URL.revokeObjectURL(a.href)}
async function exportResponses(sid){exportCSV(sid,await getResponses(sid))}
async function clearResponses(sid){if(!confirm('Delete all responses for this survey?'))return;if(state.cloud){const snap=await db.collection('surveys').doc(sid).collection('responses').get();const batch=db.batch();snap.docs.forEach(d=>batch.delete(d.ref));await batch.commit()}else{const d=localLoad();d.responses=d.responses.filter(r=>r.surveyId!==sid);localSave(d);state.responses=d.responses}results(sid);toast('Responses cleared')}
async function results(sid){
 if(state.cloud&&!state.user)return authScreen();if(state.cloud&&!surveyById(sid))await loadOwnedSurveys();const s=surveyById(sid);if(!s)return location.hash='#/';const rs=await getResponses(sid),last=rs.at(-1)?.submittedAt,completion=calcCompletion(s,rs),blocks=s.questions.map(q=>resultBlock(q,rs)).join('');
 shell(`<main class="container"><section class="hero"><div><div class="tiny muted">RESULTS</div><h1>${esc(s.title)}</h1><p>See response volume, completion, plus how people answered each question.</p></div><div class="row-actions"><a class="btn btn-secondary" href="#/builder/${sid}">Back to editor</a><button class="btn btn-secondary" onclick="exportResponses('${sid}')">Export CSV</button><button class="btn btn-danger" onclick="clearResponses('${sid}')">Clear responses</button></div></section><section class="results-grid four"><div class="card metric"><span>Total responses</span><strong>${rs.length}</strong></div><div class="card metric"><span>Completion</span><strong>${completion}%</strong></div><div class="card metric"><span>Questions</span><strong>${s.questions.length}</strong></div><div class="card metric"><span>Latest response</span><strong class="metric-date">${last?fmtDate(last):'—'}</strong></div></section>${blocks||'<div class="card empty"><h3>No questions to analyse</h3><p>Add questions, then collect responses.</p></div>'}</main>`)
}

async function render(){
 if(state.loading)return loading();const hash=location.hash||'#/';const parts=hash.replace(/^#\//,'').split('/');const route=parts[0]||'',id=parts[1];
 try{if(route==='survey'&&id)return await publicSurvey(id);if(state.cloud&&!state.user)return authScreen();if(route==='builder'&&id)return await builder(id);if(route==='results'&&id)return await results(id);return await dashboard()}catch(err){console.error(err);shell(`<main class="preview-wrap"><div class="card empty"><h3>Something went wrong</h3><p>${esc(err.message||'Please try again.')}</p><a class="btn btn-primary" href="#/">Return home</a></div></main>`,false)}
}
window.addEventListener('hashchange',render);window.addEventListener('DOMContentLoaded',init);
